import java.io.Serializable;

public class PowerPlant extends Building implements Serializable {
	public PowerPlant(String name,int power) {
		super(name, -power);
	}	//the constructor of the PowerPlant class takes as arguments a name and the amount of power generated by the power plant

	@Override
	public void morePower(int amount) {
		setPower(getPower()-amount);
	}	//The morePower method of the PowerPlant class increases the amount of power generated by the power plant by the amount of power given as argument to the method

	public static void testPowerPlant() {
		PowerPlant p = new PowerPlant("UIC Power Plant", 1000000);
		System.out.println(p.getName() == "UIC Power Plant");
		System.out.println(p.getPower() == -1000000);
		p.setPower(-2000000); // Sets the power consumed by the power plant.
		System.out.println(p.getPower() == -2000000);
		p.morePower(500000); // Increases the power generated by the power plant.
		System.out.println(p.getPower() == -2500000);
		p.morePower(-2510000); // Turn off the power plant: it now consumes electricity.
		System.out.println(p.getPower() == 10000);
	}

}
